---
abstract: 'Use the ReutersConnect API'
author:
  - 'Jerome Eteve <jerome@eteve.net>'
build_requires:
  LWP::UserAgent::Mockable: 1.1
  Test::Fatal: 0.008
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-ReutersConnect
provides:
  WebService::ReutersConnect:
    file: lib/WebService/ReutersConnect.pm
    version: 0.04
  WebService::ReutersConnect::APIResponse:
    file: lib/WebService/ReutersConnect/APIResponse.pm
    version: 0
  WebService::ReutersConnect::Category:
    file: lib/WebService/ReutersConnect/Category.pm
    version: 0
  WebService::ReutersConnect::Channel:
    file: lib/WebService/ReutersConnect/Channel.pm
    version: 0
  WebService::ReutersConnect::DB:
    file: lib/WebService/ReutersConnect/DB.pm
    version: 0
  WebService::ReutersConnect::DB::Result::Concept:
    file: lib/WebService/ReutersConnect/DB/Result/Concept.pm
    version: 0
  WebService::ReutersConnect::DB::Result::ConceptAlias:
    file: lib/WebService/ReutersConnect/DB/Result/ConceptAlias.pm
    version: 0
  WebService::ReutersConnect::Item:
    file: lib/WebService/ReutersConnect/Item.pm
    version: 0
  WebService::ReutersConnect::ResultSet:
    file: lib/WebService/ReutersConnect/ResultSet.pm
    version: 0
  WebService::ReutersConnect::XMLDocument:
    file: lib/WebService/ReutersConnect/XMLDocument.pm
    version: 0
requires:
  DBD::SQLite: 1.35
  DBIx::Class: 0.08121
  DateTime: 0.7
  DateTime::Format::ISO8601: 0.07
  File::Share: 0.02
  File::ShareDir: 1.00
  HTTP::Request: 6
  HTTP::Response: 6.01
  LWP::UserAgent: 6.03
  Log::Log4perl: 1.29
  Moose: 2.0401
  URI::Escape: 3.31
  XML::LibXML: 1.89
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
